#!/bin/bash
#PBS -l nodes=2:ppn=12,walltime=00:10:00
#PBS -q batch
#PBS -N run_integralMPI
#PBS -j oe
#PBS -V

cat $PBS_NODEFILE
export OMP_NUM_THREADS=6
cd ~/SU20/integralMPI
mpiexec -np 2 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./intMPI.cx
