#!/bin/bash
#PBS -l nodes=12:ppn=12,walltime=00:05:00
#PBS -q batch
#PBS -N run_integralMPI
#PBS -j oe
#PBS -V

export OMP_NUM_THREADS=100
cd ~/PA3
mpiexec -np 12 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./mandelbrot.cx
