#!/bin/bash
#PBS -l nodes=8:ppn=12
#PBS -l walltime=0:10:00
#PBS -q batch
#PBS -N insertion
#PBS -j oe


export OMP_NUM_THREADS=1
cd ~/FinalProj/InsertionSort
mpiexec -np 8 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./insertion.cx
